keys:
  - &thinkbook age1vrvq2q003z63v80jj84kxenp7v3m9vtxpk5vkdg322vd3mqamclszfzak6
  - &thinkbook-ssh age1czctxcq7wkv7zgx5xvdmu594yrpsf07hgx48apv5qhk3x3pqhafstxydgp
  - &fuji-server age1jqf48gux5u6r6ddclq0qncu0q6809v3tg0tk69mtupxrfwggxykq4k46kz

creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *thinkbook
      - *fuji-server
      - *thinkbook-ssh
